#include <windowserver/fontchars.h>

/*
This file was generated by a script. Any changes made to it are temporary.
See $PROJECT_ROOT/fontchars/main.py

*/

FontChar fontchar_for_char(char chr) {
	switch (chr) {
	case ' ': return (FontChar) { .width=FONTCHAR_61_W, .height=0, .raw=0 };
	case 0x61:
		return (FontChar) { .width=FONTCHAR_61_W, .height=FONTCHAR_61_H, .raw=FONTCHAR_61_RAW };
	case 0x62:
		return (FontChar) { .width=FONTCHAR_62_W, .height=FONTCHAR_62_H, .raw=FONTCHAR_62_RAW };
	case 0x63:
		return (FontChar) { .width=FONTCHAR_63_W, .height=FONTCHAR_63_H, .raw=FONTCHAR_63_RAW };
	case 0x64:
		return (FontChar) { .width=FONTCHAR_64_W, .height=FONTCHAR_64_H, .raw=FONTCHAR_64_RAW };
	case 0x65:
		return (FontChar) { .width=FONTCHAR_65_W, .height=FONTCHAR_65_H, .raw=FONTCHAR_65_RAW };
	case 0x66:
		return (FontChar) { .width=FONTCHAR_66_W, .height=FONTCHAR_66_H, .raw=FONTCHAR_66_RAW };
	case 0x67:
		return (FontChar) { .width=FONTCHAR_67_W, .height=FONTCHAR_67_H, .raw=FONTCHAR_67_RAW };
	case 0x68:
		return (FontChar) { .width=FONTCHAR_68_W, .height=FONTCHAR_68_H, .raw=FONTCHAR_68_RAW };
	case 0x69:
		return (FontChar) { .width=FONTCHAR_69_W, .height=FONTCHAR_69_H, .raw=FONTCHAR_69_RAW };
	case 0x6a:
		return (FontChar) { .width=FONTCHAR_6a_W, .height=FONTCHAR_6a_H, .raw=FONTCHAR_6a_RAW };
	case 0x6b:
		return (FontChar) { .width=FONTCHAR_6b_W, .height=FONTCHAR_6b_H, .raw=FONTCHAR_6b_RAW };
	case 0x6c:
		return (FontChar) { .width=FONTCHAR_6c_W, .height=FONTCHAR_6c_H, .raw=FONTCHAR_6c_RAW };
	case 0x6d:
		return (FontChar) { .width=FONTCHAR_6d_W, .height=FONTCHAR_6d_H, .raw=FONTCHAR_6d_RAW };
	case 0x6e:
		return (FontChar) { .width=FONTCHAR_6e_W, .height=FONTCHAR_6e_H, .raw=FONTCHAR_6e_RAW };
	case 0x6f:
		return (FontChar) { .width=FONTCHAR_6f_W, .height=FONTCHAR_6f_H, .raw=FONTCHAR_6f_RAW };
	case 0x70:
		return (FontChar) { .width=FONTCHAR_70_W, .height=FONTCHAR_70_H, .raw=FONTCHAR_70_RAW };
	case 0x71:
		return (FontChar) { .width=FONTCHAR_71_W, .height=FONTCHAR_71_H, .raw=FONTCHAR_71_RAW };
	case 0x72:
		return (FontChar) { .width=FONTCHAR_72_W, .height=FONTCHAR_72_H, .raw=FONTCHAR_72_RAW };
	case 0x73:
		return (FontChar) { .width=FONTCHAR_73_W, .height=FONTCHAR_73_H, .raw=FONTCHAR_73_RAW };
	case 0x74:
		return (FontChar) { .width=FONTCHAR_74_W, .height=FONTCHAR_74_H, .raw=FONTCHAR_74_RAW };
	case 0x75:
		return (FontChar) { .width=FONTCHAR_75_W, .height=FONTCHAR_75_H, .raw=FONTCHAR_75_RAW };
	case 0x76:
		return (FontChar) { .width=FONTCHAR_76_W, .height=FONTCHAR_76_H, .raw=FONTCHAR_76_RAW };
	case 0x77:
		return (FontChar) { .width=FONTCHAR_77_W, .height=FONTCHAR_77_H, .raw=FONTCHAR_77_RAW };
	case 0x78:
		return (FontChar) { .width=FONTCHAR_78_W, .height=FONTCHAR_78_H, .raw=FONTCHAR_78_RAW };
	case 0x79:
		return (FontChar) { .width=FONTCHAR_79_W, .height=FONTCHAR_79_H, .raw=FONTCHAR_79_RAW };
	case 0x7a:
		return (FontChar) { .width=FONTCHAR_7a_W, .height=FONTCHAR_7a_H, .raw=FONTCHAR_7a_RAW };
	case 0x41:
		return (FontChar) { .width=FONTCHAR_41_W, .height=FONTCHAR_41_H, .raw=FONTCHAR_41_RAW };
	case 0x42:
		return (FontChar) { .width=FONTCHAR_42_W, .height=FONTCHAR_42_H, .raw=FONTCHAR_42_RAW };
	case 0x43:
		return (FontChar) { .width=FONTCHAR_43_W, .height=FONTCHAR_43_H, .raw=FONTCHAR_43_RAW };
	case 0x44:
		return (FontChar) { .width=FONTCHAR_44_W, .height=FONTCHAR_44_H, .raw=FONTCHAR_44_RAW };
	case 0x45:
		return (FontChar) { .width=FONTCHAR_45_W, .height=FONTCHAR_45_H, .raw=FONTCHAR_45_RAW };
	case 0x46:
		return (FontChar) { .width=FONTCHAR_46_W, .height=FONTCHAR_46_H, .raw=FONTCHAR_46_RAW };
	case 0x47:
		return (FontChar) { .width=FONTCHAR_47_W, .height=FONTCHAR_47_H, .raw=FONTCHAR_47_RAW };
	case 0x48:
		return (FontChar) { .width=FONTCHAR_48_W, .height=FONTCHAR_48_H, .raw=FONTCHAR_48_RAW };
	case 0x49:
		return (FontChar) { .width=FONTCHAR_49_W, .height=FONTCHAR_49_H, .raw=FONTCHAR_49_RAW };
	case 0x4a:
		return (FontChar) { .width=FONTCHAR_4a_W, .height=FONTCHAR_4a_H, .raw=FONTCHAR_4a_RAW };
	case 0x4b:
		return (FontChar) { .width=FONTCHAR_4b_W, .height=FONTCHAR_4b_H, .raw=FONTCHAR_4b_RAW };
	case 0x4c:
		return (FontChar) { .width=FONTCHAR_4c_W, .height=FONTCHAR_4c_H, .raw=FONTCHAR_4c_RAW };
	case 0x4d:
		return (FontChar) { .width=FONTCHAR_4d_W, .height=FONTCHAR_4d_H, .raw=FONTCHAR_4d_RAW };
	case 0x4e:
		return (FontChar) { .width=FONTCHAR_4e_W, .height=FONTCHAR_4e_H, .raw=FONTCHAR_4e_RAW };
	case 0x4f:
		return (FontChar) { .width=FONTCHAR_4f_W, .height=FONTCHAR_4f_H, .raw=FONTCHAR_4f_RAW };
	case 0x50:
		return (FontChar) { .width=FONTCHAR_50_W, .height=FONTCHAR_50_H, .raw=FONTCHAR_50_RAW };
	case 0x51:
		return (FontChar) { .width=FONTCHAR_51_W, .height=FONTCHAR_51_H, .raw=FONTCHAR_51_RAW };
	case 0x52:
		return (FontChar) { .width=FONTCHAR_52_W, .height=FONTCHAR_52_H, .raw=FONTCHAR_52_RAW };
	case 0x53:
		return (FontChar) { .width=FONTCHAR_53_W, .height=FONTCHAR_53_H, .raw=FONTCHAR_53_RAW };
	case 0x54:
		return (FontChar) { .width=FONTCHAR_54_W, .height=FONTCHAR_54_H, .raw=FONTCHAR_54_RAW };
	case 0x55:
		return (FontChar) { .width=FONTCHAR_55_W, .height=FONTCHAR_55_H, .raw=FONTCHAR_55_RAW };
	case 0x56:
		return (FontChar) { .width=FONTCHAR_56_W, .height=FONTCHAR_56_H, .raw=FONTCHAR_56_RAW };
	case 0x57:
		return (FontChar) { .width=FONTCHAR_57_W, .height=FONTCHAR_57_H, .raw=FONTCHAR_57_RAW };
	case 0x58:
		return (FontChar) { .width=FONTCHAR_58_W, .height=FONTCHAR_58_H, .raw=FONTCHAR_58_RAW };
	case 0x59:
		return (FontChar) { .width=FONTCHAR_59_W, .height=FONTCHAR_59_H, .raw=FONTCHAR_59_RAW };
	case 0x5a:
		return (FontChar) { .width=FONTCHAR_5a_W, .height=FONTCHAR_5a_H, .raw=FONTCHAR_5a_RAW };
	case 0x30:
		return (FontChar) { .width=FONTCHAR_30_W, .height=FONTCHAR_30_H, .raw=FONTCHAR_30_RAW };
	case 0x31:
		return (FontChar) { .width=FONTCHAR_31_W, .height=FONTCHAR_31_H, .raw=FONTCHAR_31_RAW };
	case 0x32:
		return (FontChar) { .width=FONTCHAR_32_W, .height=FONTCHAR_32_H, .raw=FONTCHAR_32_RAW };
	case 0x33:
		return (FontChar) { .width=FONTCHAR_33_W, .height=FONTCHAR_33_H, .raw=FONTCHAR_33_RAW };
	case 0x34:
		return (FontChar) { .width=FONTCHAR_34_W, .height=FONTCHAR_34_H, .raw=FONTCHAR_34_RAW };
	case 0x35:
		return (FontChar) { .width=FONTCHAR_35_W, .height=FONTCHAR_35_H, .raw=FONTCHAR_35_RAW };
	case 0x36:
		return (FontChar) { .width=FONTCHAR_36_W, .height=FONTCHAR_36_H, .raw=FONTCHAR_36_RAW };
	case 0x37:
		return (FontChar) { .width=FONTCHAR_37_W, .height=FONTCHAR_37_H, .raw=FONTCHAR_37_RAW };
	case 0x38:
		return (FontChar) { .width=FONTCHAR_38_W, .height=FONTCHAR_38_H, .raw=FONTCHAR_38_RAW };
	case 0x39:
		return (FontChar) { .width=FONTCHAR_39_W, .height=FONTCHAR_39_H, .raw=FONTCHAR_39_RAW };
	case 0x2d:
		return (FontChar) { .width=FONTCHAR_2d_W, .height=FONTCHAR_2d_H, .raw=FONTCHAR_2d_RAW };
	case 0x2b:
		return (FontChar) { .width=FONTCHAR_2b_W, .height=FONTCHAR_2b_H, .raw=FONTCHAR_2b_RAW };
	case 0x3d:
		return (FontChar) { .width=FONTCHAR_3d_W, .height=FONTCHAR_3d_H, .raw=FONTCHAR_3d_RAW };
	case 0x2a:
		return (FontChar) { .width=FONTCHAR_2a_W, .height=FONTCHAR_2a_H, .raw=FONTCHAR_2a_RAW };
	case 0x2f:
		return (FontChar) { .width=FONTCHAR_2f_W, .height=FONTCHAR_2f_H, .raw=FONTCHAR_2f_RAW };
	case 0x5c:
		return (FontChar) { .width=FONTCHAR_5c_W, .height=FONTCHAR_5c_H, .raw=FONTCHAR_5c_RAW };
	case 0x3f:
		return (FontChar) { .width=FONTCHAR_3f_W, .height=FONTCHAR_3f_H, .raw=FONTCHAR_3f_RAW };
	case 0x28:
		return (FontChar) { .width=FONTCHAR_28_W, .height=FONTCHAR_28_H, .raw=FONTCHAR_28_RAW };
	case 0x29:
		return (FontChar) { .width=FONTCHAR_29_W, .height=FONTCHAR_29_H, .raw=FONTCHAR_29_RAW };
	case 0x5b:
		return (FontChar) { .width=FONTCHAR_5b_W, .height=FONTCHAR_5b_H, .raw=FONTCHAR_5b_RAW };
	case 0x5d:
		return (FontChar) { .width=FONTCHAR_5d_W, .height=FONTCHAR_5d_H, .raw=FONTCHAR_5d_RAW };
	case 0x7b:
		return (FontChar) { .width=FONTCHAR_7b_W, .height=FONTCHAR_7b_H, .raw=FONTCHAR_7b_RAW };
	case 0x7d:
		return (FontChar) { .width=FONTCHAR_7d_W, .height=FONTCHAR_7d_H, .raw=FONTCHAR_7d_RAW };
	case 0x27:
		return (FontChar) { .width=FONTCHAR_27_W, .height=FONTCHAR_27_H, .raw=FONTCHAR_27_RAW };
	case 0x22:
		return (FontChar) { .width=FONTCHAR_22_W, .height=FONTCHAR_22_H, .raw=FONTCHAR_22_RAW };
	case 0x3c:
		return (FontChar) { .width=FONTCHAR_3c_W, .height=FONTCHAR_3c_H, .raw=FONTCHAR_3c_RAW };
	case 0x3e:
		return (FontChar) { .width=FONTCHAR_3e_W, .height=FONTCHAR_3e_H, .raw=FONTCHAR_3e_RAW };
	case 0x2c:
		return (FontChar) { .width=FONTCHAR_2c_W, .height=FONTCHAR_2c_H, .raw=FONTCHAR_2c_RAW };
	case 0x2e:
		return (FontChar) { .width=FONTCHAR_2e_W, .height=FONTCHAR_2e_H, .raw=FONTCHAR_2e_RAW };
	case 0x23:
		return (FontChar) { .width=FONTCHAR_23_W, .height=FONTCHAR_23_H, .raw=FONTCHAR_23_RAW };
	case 0x21:
		return (FontChar) { .width=FONTCHAR_21_W, .height=FONTCHAR_21_H, .raw=FONTCHAR_21_RAW };
	default: return (FontChar) { .width=0, .height=0, .raw=0 };
	}
}
